apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  value_from_values: {{ .Values.fruit }}
  value_from_charts: {{ .Chart.Name }}
  value_from_subcharts: {{ .Subcharts.sample.fruit }}