# we use quote template function for get value quoted("").
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ quote .Values.favorite.drink }}
  drinkRe: {{ .Values.favorite.drink | repeat 3 | quote }}
  food: {{ .Values.favorite.food | quote }}
  foodUp: {{ .Values.favorite.food | upper | quote }}
